# Generated by Django 5.1.7 on 2025-03-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
